# Generated by Django 3.2 on 2023-04-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
